### ISSUE TITLE
'GPL-3.0-only' has 'GPL-3.0-or-later' as an alias

### ISSUE THREAD

**Issue by Phrohdoh** [amzn/askalono#45]
I ran `askalono identify --optimize path/to/file.rs` and got the following.

```
License: Unknown
Score: 0.221
Containing:
  License: GPL-3.0-only (license header)
  Score: 0.946
  Lines: 4 - 15
  Aliases: GPL-3.0-or-later
```

Using `GPL-3.0-only` is different from `GPL-3.0-or-later`, why are they aliases of each other?

Is this something `askalono` controls/determines or are aliases driven by SPDX data?
